# Generated by Django 3.2.3 on 2022-10-04 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='Sin Nombre', max_length=255, verbose_name='Nombre'),
        ),
    ]
