# Generated by Django 3.2.3 on 2022-10-17 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_sistema'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rol',
            options={'verbose_name_plural': 'Roles de usuario'},
        ),
    ]
