# Generated by Django 3.2.3 on 2022-10-19 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_rol_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='role',
            field=models.CharField(choices=[(1, 'Administrador'), (2, 'Operador'), (3, 'Usuario RODA')], default='Sin Rol', max_length=30, null=True, verbose_name='Rol'),
        ),
    ]
