# Generated by Django 3.2.3 on 2022-09-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credencial', models.CharField(blank=True, max_length=255, unique=True, verbose_name='Credencial')),
                ('name_sis', models.CharField(blank=True, max_length=255, unique=True, verbose_name='Nombre de Sistema')),
                ('url', models.CharField(blank=True, max_length=255, unique=True, verbose_name='Url')),
            ],
        ),
    ]
