# Generated by Django 3.2.3 on 2022-09-30 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_rol_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Rol',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
