# Generated by Django 3.2.3 on 2022-10-05 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20220930_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_cli', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre cliente')),
                ('rut_cliente', models.CharField(blank=True, max_length=255, null=True, verbose_name='Rut Cliente')),
                ('razon_social', models.CharField(blank=True, max_length=255, null=True, verbose_name='Razon social')),
                ('direccion_sucursal_cliente', models.CharField(blank=True, max_length=255, null=True, verbose_name='Direccion sucursal')),
                ('is_active', models.BooleanField(default=True)),
                ('sistema', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.sistema')),
            ],
        ),
    ]
