# Generated by Django 3.2.3 on 2022-10-13 15:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_alter_cliente_sistema'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comuna', models.CharField(max_length=255, null=True, verbose_name='Comuna')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_proveedor', models.CharField(max_length=255, verbose_name='Nombre Distribuidor')),
                ('rut_proveedor', models.CharField(max_length=255, verbose_name='Rut Proveedor')),
                ('contacto', models.CharField(max_length=255, verbose_name='Contacto')),
                ('servicio', models.CharField(choices=[('L', 'Luz'), ('A', 'Agua'), ('G', 'Gas')], max_length=255, verbose_name='Tipo Servicio')),
            ],
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zona', models.CharField(max_length=255, null=True, verbose_name='Zona')),
            ],
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='direccion_sucursal_cliente',
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_sucursal', models.CharField(max_length=255, verbose_name='Nombre Unidad')),
                ('num_cliente', models.IntegerField(verbose_name='Numero Cliente')),
                ('cod', models.IntegerField(verbose_name='Codigo')),
                ('is_active', models.BooleanField(default=True)),
                ('direccion', models.CharField(max_length=255, verbose_name='Direccion')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.cliente')),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.comuna')),
                ('proveedor', models.ManyToManyField(related_name='Proveedor', to='management.Proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=255, null=True, verbose_name='Region')),
                ('zona', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='management.zona')),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_doc', models.CharField(default='Documento', max_length=255, verbose_name='Documento')),
                ('fecha_creacion', models.DateField()),
                ('myfile', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['json'])])),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.cliente')),
            ],
        ),
        migrations.AddField(
            model_name='comuna',
            name='region',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='management.region'),
        ),
    ]
