# Generated by Django 3.2.3 on 2022-10-16 23:30

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_auto_20221013_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_doc', models.CharField(default='Documento', max_length=255, verbose_name='Documento')),
                ('fecha_creacion', models.DateField(verbose_name=datetime.datetime(2022, 10, 16, 20, 30, 58, 138173))),
                ('procesado', models.BooleanField(default=True)),
                ('documento', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['json', 'pdf'])])),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.cliente')),
            ],
        ),
        migrations.DeleteModel(
            name='Documento',
        ),
    ]
