# Generated by Django 3.2.3 on 2022-10-17 00:18

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_alter_documentos_fecha_creacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_doc', models.CharField(default='Documento', max_length=255, verbose_name='Documento')),
                ('folio', models.CharField(max_length=255, verbose_name='Folio')),
                ('fecha_procesado', models.DateTimeField(verbose_name=datetime.datetime(2022, 10, 16, 21, 18, 19, 328731))),
                ('procesado', models.BooleanField(default=False)),
                ('documento', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['json', 'pdf'])])),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.cliente')),
            ],
        ),
        migrations.DeleteModel(
            name='Documentos',
        ),
    ]
