# Generated by Django 3.2.3 on 2022-10-17 01:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_auto_20221016_2118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'verbose_name_plural': 'Proveedores'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name_plural': 'Regiones'},
        ),
        migrations.AlterModelOptions(
            name='sistema',
            options={'verbose_name_plural': 'Sistema'},
        ),
        migrations.AlterModelOptions(
            name='sucursal',
            options={'verbose_name_plural': 'Sucursales'},
        ),
        migrations.AlterModelOptions(
            name='zona',
            options={'verbose_name_plural': 'Zonas'},
        ),
        migrations.AlterField(
            model_name='documento',
            name='fecha_procesado',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 10, 16, 22, 35, 1, 941527)),
        ),
    ]
