# Generated by Django 3.2.3 on 2022-10-17 01:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_auto_20221016_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='rut_cliente',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Rut Cliente'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='fecha_procesado',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 10, 16, 22, 58, 27, 749825)),
        ),
    ]
