# Generated by Django 3.2.3 on 2022-10-17 02:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_auto_20221016_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='rut_cliente',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Rut Cliente'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='fecha_procesado',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 10, 16, 23, 12, 5, 828413)),
        ),
    ]
