# Generated by Django 3.2.3 on 2022-10-17 02:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0015_alter_documento_fecha_procesado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='rut_cliente',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Rut Cliente'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='fecha_procesado',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 10, 16, 23, 28, 48, 598124)),
        ),
    ]
