# Generated by Django 3.2.3 on 2022-10-17 02:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_auto_20221016_2328'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sistema',
            options={'verbose_name': 'Configuracion del sistema'},
        ),
        migrations.AlterField(
            model_name='documento',
            name='fecha_procesado',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 10, 16, 23, 48, 49, 773162)),
        ),
    ]
