# Generated by Django 3.2.3 on 2022-10-19 00:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0017_auto_20221016_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='rut_cliente',
            field=models.CharField(default='Sin Rut', max_length=10, unique=True, verbose_name='Rut Cliente'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='fecha_procesado',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 10, 18, 21, 33, 14, 652787)),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='rut_proveedor',
            field=models.CharField(max_length=255, unique=True, verbose_name='Rut Proveedor'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='servicio',
            field=models.CharField(choices=[(1, 'Luz'), (2, 'Agua'), (3, 'Gas')], max_length=255, verbose_name='Tipo Servicio'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='cod',
            field=models.IntegerField(unique=True, verbose_name='Codigo'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='num_cliente',
            field=models.IntegerField(unique=True, verbose_name='Numero Cliente'),
        ),
    ]
