# Generated by Django 3.2.3 on 2022-10-19 16:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0027_alter_documento_fecha_procesado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='fecha_procesado',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 10, 19, 13, 42, 11, 798757)),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='servicio',
            field=models.CharField(choices=[('1', 'Luz'), ('2', 'Agua'), ('3', 'Gas')], max_length=255, verbose_name='Tipo Servicio'),
        ),
    ]
