# Generated by Django 3.2.3 on 2022-10-20 22:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0029_auto_20221019_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='cliente',
        ),
        migrations.AddField(
            model_name='documento',
            name='sucursal',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='management.sucursal'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='fecha_procesado',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 10, 20, 19, 11, 7, 227550)),
        ),
    ]
