# Generated by Django 3.2.3 on 2022-10-20 22:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0030_auto_20221020_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='fecha_procesado',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
