# Generated by Django 3.2.3 on 2022-10-20 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0031_alter_documento_fecha_procesado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursal',
            name='nom_sucursal',
            field=models.CharField(max_length=255, null=True, verbose_name='Nombre Unidad'),
        ),
    ]
