# Generated by Django 3.2.3 on 2022-10-20 23:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0032_alter_sucursal_nom_sucursal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato_servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('proveedor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='management.proveedor')),
                ('sucursal', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='management.sucursal')),
            ],
        ),
    ]
