# Generated by Django 3.2.3 on 2022-10-20 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0033_contrato_servicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sucursal',
            name='proveedor',
        ),
    ]
