# Generated by Django 3.2.3 on 2022-10-21 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0036_alter_contrato_servicio_sucursal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato_servicio',
            name='sucursal',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='management.sucursal'),
        ),
    ]
