# Generated by Django 3.2.3 on 2022-11-02 05:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0038_auto_20221023_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sistema',
            name='url',
        ),
        migrations.AlterField(
            model_name='sistema',
            name='credencial',
            field=models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['json'])]),
        ),
    ]
