# Generated by Django 3.2.3 on 2022-11-02 03:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0038_auto_20221023_2244'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.CharField(max_length=255, null=True, verbose_name='Servicio')),
            ],
            options={
                'verbose_name_plural': 'Servicios',
            },
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='servicio',
        ),
        migrations.RemoveField(
            model_name='sistema',
            name='url',
        ),
        migrations.AlterField(
            model_name='sistema',
            name='credencial',
            field=models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['json'])]),
        ),
    ]
