# Generated by Django 3.2.3 on 2022-11-04 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0040_plantilla'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='servicio',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.servicio'),
        ),
    ]
