# Generated by Django 3.2.3 on 2022-11-04 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0041_proveedor_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
