# Generated by Django 3.2.3 on 2022-11-04 01:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0042_proveedor_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantilla',
            name='tablas_config',
            field=models.FileField(null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['json'])]),
        ),
    ]
