# Generated by Django 3.2.3 on 2022-11-08 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0043_alter_plantilla_tablas_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='rut_sucursal',
            field=models.CharField(default=20, max_length=255, unique=True, verbose_name='Rut Sucursal'),
            preserve_default=False,
        ),
    ]
