# Generated by Django 3.2.3 on 2022-11-09 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0044_auto_20221107_2113'),
        ('management', '0044_sucursal_rut_sucursal'),
    ]

    operations = [
    ]
