# Generated by Django 3.2.3 on 2022-11-12 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0046_auto_20221109_0220'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api', models.CharField(max_length=255, verbose_name='URL')),
                ('id_user', models.IntegerField(verbose_name='Id Usuario')),
                ('cliente', models.CharField(default='No Aplica', max_length=255, verbose_name='Cliente')),
                ('payload', models.CharField(max_length=255, verbose_name='Payload')),
                ('method', models.CharField(max_length=255, verbose_name='Tipo de peticion')),
                ('response', models.TextField()),
                ('status_code', models.PositiveSmallIntegerField(verbose_name='Status Respuesta')),
            ],
        ),
    ]
