# Generated by Django 3.2.3 on 2022-11-21 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0051_alter_plantilla_queries_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logsistema',
            name='api',
            field=models.CharField(default=None, max_length=255, null=True, verbose_name='URL'),
        ),
    ]
