# Generated by Django 3.2.3 on 2022-11-21 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0052_alter_logsistema_api'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logsistema',
            name='id_user',
            field=models.IntegerField(default=None, null=True, verbose_name='Id Usuario'),
        ),
    ]
