# Generated by Django 3.2.3 on 2022-11-20 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0053_auto_20221119_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cron',
            name='desactivar',
        ),
        migrations.AddField(
            model_name='cron',
            name='is_active',
            field=models.BooleanField(choices=[(True, 'Acticado'), (False, 'Desactivado')], default=True),
        ),
    ]
