# Generated by Django 3.2.3 on 2022-11-21 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0053_alter_logsistema_id_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logsistema',
            name='api',
            field=models.CharField(default='URL', max_length=255, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='logsistema',
            name='id_user',
            field=models.IntegerField(default=0, verbose_name='Id Usuario'),
        ),
    ]
