# Generated by Django 3.2.3 on 2022-11-20 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0054_auto_20221119_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='cron',
            name='sistema',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.sistema'),
        ),
    ]
