# Generated by Django 3.2.3 on 2022-11-21 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0054_auto_20221120_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logsistema',
            name='payload',
            field=models.CharField(default='Payload', max_length=255, verbose_name='Payload'),
        ),
    ]
