# Generated by Django 3.2.3 on 2022-11-21 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0055_alter_logsistema_payload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logsistema',
            name='method',
            field=models.CharField(default='Metodo', max_length=255, verbose_name='Tipo de peticion'),
        ),
    ]
