# Generated by Django 3.2.3 on 2022-11-24 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0059_auto_20221122_2109'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigCron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(1, 'En espera'), (2, 'Recopilando DATA'), (3, 'Procesando DATA'), (4, 'Finalizando'), (5, 'Detenido')], default='5', max_length=100, verbose_name='Status')),
                ('cursor', models.IntegerField(default=0, verbose_name='Cursor')),
                ('is_active', models.BooleanField(choices=[(True, 'Activado'), (False, 'Desactivado')], default=True)),
                ('hora_exec', models.TimeField(default='5:00')),
            ],
            options={
                'verbose_name': 'Configuracion de CRON',
            },
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='rut_proveedor',
            field=models.CharField(max_length=255, unique=True, verbose_name='Rut Proveedor'),
        ),
    ]
