# Generated by Django 3.2.3 on 2022-11-22 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0059_configcron'),
    ]

    operations = [
        migrations.AddField(
            model_name='configcron',
            name='status',
            field=models.CharField(default='Inactivo', max_length=100, verbose_name='Status'),
        ),
    ]
