# Generated by Django 3.2.3 on 2022-11-24 22:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0061_alter_configcron_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='configcron',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
