# Generated by Django 3.2.3 on 2022-11-24 22:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0062_configcron_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configcron',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
