# Generated by Django 3.2.3 on 2022-11-26 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0065_alter_configcron_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursal',
            name='cod',
            field=models.IntegerField(db_index=True, unique=True, verbose_name='Codigo'),
        ),
    ]
