# Generated by Django 3.2.3 on 2022-11-26 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0066_alter_sucursal_cod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursal',
            name='cod',
            field=models.IntegerField(unique=True, verbose_name='Codigo'),
        ),
        migrations.AddIndex(
            model_name='sucursal',
            index=models.Index(fields=['cod'], name='management__cod_654eed_idx'),
        ),
    ]
